### PR TITLE
auto-select-first-item

### PR DESCRIPTION
**Pull request by muthukumarse**
Made first item auto selected up on context menu suggestion. Also removed condition to avoid lost focus on TAB key when minQueryLength=0

### CODE REVIEW

**Comment by Billy-** [comment]
@muthukumarse Looks like you broke the tests. Those will probably need be fixed before this is merged.

**Comment by Billy-** [comment]
re #55

**Comment by muthukumarse** [comment]
@Billy
Can You mention what is the issue.

**Comment by muthukumarse** [comment]
@Billy- correct the issue PR#74

**Comment by i-like-robots** [comment]
Thanks for your time implementing this feature @muthukumarse. As mentioned in #55 this feature conflicts with the `allowNew` option. You're implementation is good so I'll have a think about how to reconcile the two.

**Comment by muthukumarse** [comment]
👍

**Comment by gabrielbhansen** [comment]
@i-like-robots Has there been any progress on this pull request. We would very much enjoy this feature :)

**Comment by eivindml-solvr** [comment]
Could we merge this pull request? I'm happy to help it depend on `allowNew` and fix conflicts.

**Comment by i-like-robots** [comment]
Closing as this feature is now supported in v7.

**Pull request closed without merging**
