### PR TITLE
Handle input blur with event

### PR DESCRIPTION
**Pull request by jedrzejiwanicki**
I added input blur handler. `SyntheticEvent` is passed as argument when user blurs the input field.

### CODE REVIEW

**Comment by i-like-robots** [comment]
Hello @jedrzejiwanicki thank you for this. Could you please clarify what the difference between this and the existing `handleBlur` callback is?

**Comment by jedrzejiwanicki** [comment]
Hi, the goal was to pass the event as current solution does not provide any parameter.

But I think now that instead of creating another handler we could just pass `query` from state, and add option to add a tag on blur. What do you think about this solution?

**Comment by i-like-robots** [comment]
Ah, you're right - would passing the event to the current `handleBlur` callback suffice?

**Comment by jedrzejiwanicki** [comment]
Please take a look at current solution. I extracted termination logic to handle adding tag from suggestion list.

**Comment by i-like-robots** [comment]
Thank you for this PR @jedrzejiwanicki, it's good stuff.

The add on blur functionality appears to be implemented in the same wat as #138 so I'll toss a coin to see which to merge. Thanks again.

**Comment by i-like-robots** [comment]
Hello again, I have now merged #138 - I chose that PR over this one because it had the updates to the readme included - but thank you very much for your work on this.

**Pull request closed without merging**
