### PR TITLE
added patch to recognize some delimiter characters for soft keyboards

### PR DESCRIPTION
**Pull request by alanllamas**
added really simple patch to recognize some characters from soft keyboards, i hope this patch leads to a better solution, if you have some ideas and want me to implement them please contact me, i`d love to contribute

### CODE REVIEW

**Comment by i-like-robots** [comment]
Thanks for taking the time to submit this @alanllamas but I'm afraid I don't understand what the issue is and how this change might fix it.

The `delimeterChars` prop is intended to be an array of literal characters (`KeyboardEvent.key`). The `delimeters` prop is a list of key codes (which correspond to `KeyboardEvent.keyCode`).

Does configuring the either the `delimeters` or `delimeterChars` prop with the extra characters help you to achieve your task?

Or, have you found a problem with the timing of keyboard events from soft keyboards or an issue with key codes not always being the same?

**Comment by alanllamas** [comment]
Im sorry i didn`t explain the issue, it happens that i couldn't recognize a keycode from soft keyboards, and always got 229, 0 or something like undefined or unassigned at code, keycode, and even charcode.

The solution was (and it is definitely just a patch) obtain the character tapped by the user and match it to an array, with hardcoded keycode values for every delimiter i needed, and passed another comparison to check if the value was at the delimiters prop that was being passed.

Most of all, it is a UX bug on mobile  version because event keycodes doesn't match any character in mobile , so the only way to add a tag was addonBlur and you had to tap at the tag input again to submit another to the list.

It happens with android soft keyboards, was tested in browserstack and mobile devices on hand.

if you consider it something to fix, and this approach might solve it i can work on the patch so it becomes a complete solution for soft keyboard issues about keycodes.

i attache some links that show the issue in general:

https://stackoverflow.com/questions/36753548/keycode-on-android-is-always-229
https://bugs.chromium.org/p/chromium/issues/detail?id=118639
https://social.msdn.microsoft.com/Forums/en-US/d9ac5d52-55f5-4e8f-b074-22323834a09c/keydown-event-always-returns-keycode-229?forum=vssmartdevicesvbcs

**Comment by i-like-robots** [comment]
Thanks for the extra information @alanllamas, that's excellent. I'll try to get hold of a device to recreate this next week.

Would you mind creating a separate issue to track this problem?

**Comment by i-like-robots** [comment]
Closing this in favour of #181

**Pull request closed without merging**
