### PR TITLE
Ignore filter suggestions and show dropdown if suggestions are exists

### PR DESCRIPTION
**Pull request by voleoo**

### CODE REVIEW

**Comment by i-like-robots** [comment]
Thanks for taking the time to put this together @voleoo - but I'm not really sure what the use case for this option is, would you please provide an example for why this might be useful?

**Comment by voleoo** [comment]
The same issue like https://github.com/i-like-robots/react-tags/issues/141#issuecomment-448222477

**Comment by i-like-robots** [comment]
Ah, I see. Perhaps as requested in the original issue an option to define the filter function itself might be more flexible going forward. For the case where implementers wish to disable filtering entirely the option could be set to `() => true`, what do you think?

**Comment by voleoo** [comment]
Yes, I agree with you, will implement it on the next week ;-)

**Comment by paulshannon** [comment]
My team is currently blocked on this; if no further work has happened we could devote some time to it. (@voleoo)

**Comment by paulshannon** [comment]
This would be redundant with #153

**Comment by i-like-robots** [comment]
Closing in favour of #153

**Pull request closed without merging**
